services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379

  mongodb-server:
    image: mongo:latest
    container_name: mongodb-server
    ports:
        - 27017:27017

  mqtt-server:
    image: eclipse-mosquitto:latest
    container_name: mqtt-server
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    
  fake-device:
    image: node:16-alpine
    container_name: fake-device
    stdin_open: true 
    tty: true        
    ports:
      - 8099:8099
    working_dir: /app
    volumes:
      - ./fake-device/app:/app